### ISSUE TITLE
TabNine not suggesting auto completions

### ISSUE THREAD

**Issue by IPWright83** [codota/tabnine-sublime#72] opened 2020-10-13 10:08 UTC
- OS version: Ubuntu 18.04.4
 - Editor version: Sublime Text 3 Build 3210
 - Programming language: JavaScript
 - TabNine extension version: 3.0.6
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**
TabNine stops working - there are no suggestions in the auto complete:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/home/iw651/.config/sublime-text-3/Packages/TabNine/completions/completions_v2.py", line 204, in on_activated_async
    }
  File "/home/iw651/.config/sublime-text-3/Packages/TabNine/tab_nine_process.py", line 116, in request
    req += '\n'
AttributeError: 'NoneType' object has no attribute 'dumps'
```

**Comment by dimacodota** [comment] 2020-10-13 11:18
@IPWright83  can you please open the Sublime Console (`View -> Show Console`) and run the following code:
`import json; json.__file__`  ?

**Comment by IPWright83** [comment] 2020-10-13 12:43
I get this output

**Comment by dimacodota** [comment] 2020-10-13 14:00
Thank you  @IPWright83 . I will keep you posted. does it reproduce after restart?

**Comment by davidhariri** [comment] 2020-10-14 14:39
Seeing this too. No completions.

**Comment by dimacodota** [comment] 2020-10-18 14:08
@IPWright83 , I wasn't able to reproduce the issue, however, version 3.0.7 is trying to fix it, please confirm if the issue is resolved. 
Thanks

**Comment by davidhariri** [comment] 2020-10-19 13:14
> @IPWright83 , @davidhariri - I wasn't able to reproduce the issue, however, version 3.0.7 is trying to fix it, please confirm if the issue is resolved.
> Thanks

The most recent update has resolved my issue. Thanks @dimacodota 👏

**Comment by dimacodota** [comment] 2020-10-19 13:42
Great! closing the issue

**Closed by dimacodota** 2020-10-19 13:42 UTC
Labels: Type: bug

**Comment by jsheebs104** [comment] 2021-11-10 01:40
What about parameter/argument doc suggestions? Is this even a feature with TabNine? Because tab + anything or nothing does not work in any IDE or TE in any way, shape, or form whatsoever.
